### ISSUE TITLE
Interactive demo

### ISSUE THREAD

**Issue by ZiadJ** [konrazem/Freelife#1]
I'm finding the concepts here quite interesting and would like to make an interactive demo out of it so feel free to let me know if there's any possibility to collaborate. Feel free to add me on fb.com/ziad.jeeroburkhan if you'd prefer a direct conversation instead.

**Comment by Darnok11** [comment]
ZiadJ thank you very much of course I will contact you soon. We need to add workfiles and make some little changes also in Redme. I did fast video and added TVP to it also, dont know if they want to colaborate.
https://youtu.be/ZSfL9prJtoM

**Comment by ZiadJ** [comment]
I'm working on a website right now to allow RBE supporters to collaborate. The thing is TVP will not collaborate with external groups so you'd have to join them to get any support from them. However they'll most probably dictate you there and since they're after a full fledged city I'm not sure they'll agree with smaller scale projects like yours. However I'm for doing it on a smaller scale fast than wait for decades get the funds for a larger city. You can access the website from a temporary domain already here: [www.hopeproject.ml](www.hopeproject.ml) if you want to ge an idea. 
I'm also working on a food growing robot a bit like Farmbot but costing less than $1k and able to feed several families on its own. I'm also working on a group decision and resource management system so there's a lot of stuff I'm doing here and I wish I could share the load somehow.

**Comment by Darnok11** [comment]
Great ZiadJ I admire you work! Thank you for good advice. I think similar platform is https://freeworldone.com/ for projects like this. On z-day in Frankfurt we have contact with free world charter, Peter Joseph and open source ecology we hope they will also help.

**Comment by ZiadJ** [comment]
Ok, since you haven't mention anything about the possibility of collaborationg I guess you're not interested. The minimum requirement for an effective collaboration platform is a forum and the freeworldone.com makes no mention of it so it's a no go as well for me.

**Comment by ZiadJ** [comment]
Open Source Ecology is a fine group and I'm planning to join them at some point. There's [onecommunityglobal.org](http://onecommunityglobal.org) too out there but again no forum. TZM has one but it's doesn't have a voting system and probably won't since it's based on an older software that's hard to upgrade.

**Comment by Darnok11** [comment]
ZiadJ Im sorry but GitHub flagged my account and I didn't see that you replayed. Today I wrote to freeworldone.com to consider this project. The project just started and I'm just learning how to collaborate on github so please be patient. The issue is "Interactive demo" I will try to put more materials for it soon if you still want to make it.

**Comment by ZiadJ** [comment]
Ok, but since you didn't respond I've already started working on my own version separately so it's up to you. The model I came up with is for 96 people and has a different layout which I think will better satisfy the needs of it's participants.

**Comment by Darnok11** [comment]
@ZiadJ  what doesn't mean own version? Own version of all project or interactive demo. This projects fits to N number of houses. If you think different structure is better please explain why. I made some glimps why circural structure. I have made this project to collaborate of course because of synergy of open source ;)

**Comment by ZiadJ** [comment]
I've asked you to add me on Facebook already since it's way more practical to just chat there. Did you notice? I don't see us going far if I'm going to send you a message and you're going to take several days to respond. Sorry, that's not the kind of collaboration I had in mind but thanks a lot for sharing the screenshots.

**Comment by Darnok11** [comment]
I didn't get any invite from you. Thank you for chat and good luck

2018-04-18 15:27 GMT+02:00 Ziad Jeeroburkhan <notifications@github.com>:

**Comment by ZiadJ** [comment]
I mentioned my FB url in the first message and that was two weeks ago.
